spring:
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8002
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  routes:
    api-order:
      path: /api/order/**
      serviceId: oms-orderBill
    api-admin:
      path: /api/admin/**
      serviceId: api-admin
    api-sso:
      path: /api/sso/**
      serviceId: api-sso
  sensitiveHeaders: \*\  


  
                      
       